[build-system]
requires = ["setuptools>=69", "wheel", "cffi"]
build-backend = "setuptools.build_meta"

[project]
name = "ZShooter-DRP"
version = "0.0.1"
dependencies = [
    "astropy",
    "numpy",
    "matplotlib",
    "PyYAML",
    "pyreduce-astro",
    "tqdm",
]
description = "ZShooter Data Reduction Pipeline"
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "Jeb Bailey", email = "jibailey@caltech.edu" },
    { name = "Yashvi Sharma", email = "yssharma@caltech.edu" }]
license = { text = "MIT" }

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
ZSHOOTER = ["*.yaml", "*.npy"]
