trace:
  filter_y: 100  # whittaker penalty, chosen against the ScopeSim trace model
  min_cluster: 20000
#  filter_type: boxcar
  border_width: 0

curvature:
  window_width: 9

norm_flat:
  extraction_height: 50
  threshold: 100

wavecal_init:
  atlas: "zshooter"
  medium: 'vac'
  resid_delta: 100000
  smoothing: 1
  edge_margin: 0
  wave_delta: 50
  cutoff: 0.0001
  match_tolerance: 20.0
  degree: 1
  width_min: 0.1

wavecal:
  atlas: "zshooter"
  degree: 3