__instrument__: ZSHOOTER
__inherits__: defaults/settings.json

bias:
  degree: 0

flat:
  bias_scaling: exposure_time
  plot: False

trace:
  degree: 4
  bias_scaling: exposure_time
  filter_y: 30
  filter_type: gaussian
  min_cluster: 20000
  noise_relative: 0.001
  border_width: 40
  manual: false
  min_width: 0.5
  split_sigma: 5

#scatter:
#  bias_scaling: exposure_time
#  extraction_height: 0.9
#  border_width: 20

norm_flat:
#  smooth_slitfunction: 2
#  smooth_spectrum: 0
  extraction_height: 0.9
  swath_width: 200
  threshold: 100

curvature:
  dimensionality: 2D
  curve_degree: 1
  degree: [1, 1]
  curve_height: 20
  extraction_height: 10
  peak_width: 1
  peak_threshold: 100

wavecal_master:
  extraction_method: simple
  extraction_height: 30
  bias_scaling: exposure_time

wavecal_init:
  atlas: "thar"
  medium: 'vac'
  resid_delta: 2000
  edge_margin: 10
  width_min: 0.01
  width_max: 8
  wave_delta: 20
  cutoff: 0.0001
  plot: False

wavecal:
  threshold: 100
  iterations: 3
  dimensionality: 2D
  degree: [5, 5]
  manual: false
  shift_window: 0

science:
  bias_scaling: exposure_time
  oversampling: 10
  extraction_height: 1
  swath_width: 200
  smooth_slitfunction: 2
  smooth_spectrum: 0
  maxiter: 5