__instrument__: ZSHOOTER
__inherits__: defaults/settings.json

bias:
  degree: 0

flat:
  bias_scaling: exposure_time
  plot: False

trace:
  degree: 4
  bias_scaling: exposure_time
  filter_y: 20
  filter_type: gaussian
  min_cluster: 20000
  noise_relative: 0.001
  border_width: 0
  manual: false
  min_width: 0.5
  split_sigma: 5
  plot: True

#scatter:
#  bias_scaling: exposure_time
#  extraction_height: 0.9
#  border_width: 20

norm_flat:
  extraction_height: 50
  threshold: 100
  plot: False

curvature:
  dimensionality: 2D
  curve_degree: 1
  degree: [3, 3]
  curve_height: 10
  extraction_height: 50
  peak_width: 1
  peak_threshold: 10
  plot: False

wavecal_master:
  extraction_method: simple
  extraction_height: 50
  plot: False

wavecal_init:
  atlas: "thar"
  medium: 'air'
  resid_delta: 100000
  smoothing: 1
  edge_margin: 0
  wave_delta: 20
  cutoff: 0.001
  match_tolerance: 1.0
  plot: False

wavecal:
  atlas: "thar"
  threshold: 200
  dimensionality: 1D
  shift_window: 0.0
  nstep: 1
  degree: 4
  plot: True

science:
#  bias_scaling: exposure_time
#  oversampling: 10
  extraction_height: 40
#  swath_width: 200
#  smooth_slitfunction: 2
#  smooth_spectrum: 0.1
#  maxiter: 5
  plot: False