__instrument__: ZSHOOTER
__inherits__: defaults/settings.json

bias:
  degree: 0

flat:
  bias_scaling: exposure_time
  plot: False

trace:
  degree: 4
  bias_scaling: exposure_time
  filter_y: null
  filter_type: gaussian
  min_cluster: 20000
  noise_relative: 0.001
  border_width: 40
  manual: false
  min_width: 0.5
  split_sigma: 5

scatter:
  bias_scaling: exposure_time
  extraction_height: 0.9
  border_width: 20

norm_flat:
  smooth_slitfunction: 0.9
  smooth_spectrum: 0
  extraction_height: 0.9
  oversampling: 8
  swath_width: 10
  threshold: 50
  maxiter: 3

curvature:
  dimensionality: 2D
  curve_degree: 1
  curve_height: 0.9
  extraction_height: 1
  degree:
    - 1
    - 1

wavecal_master:
  extraction_method: simple
  bias_scaling: exposure_time

wavecal:
  threshold: 200
  iterations: 3
  dimensionality: 2D
  degree:
    - 7
    - 8
  manual: false
  shift_window: 0

science:
  bias_scaling: exposure_time
  oversampling: 10
  extraction_height: 1
  swath_width: 1000
  smooth_slitfunction: 2
  smooth_spectrum: 0
  maxiter: 5